export default {
  login: 'jos3ph-m',
  id: 53497675,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/53497675?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jos3ph-m',
  html_url: 'https://github.com/jos3ph-m',
  followers_url: 'https://api.github.com/users/jos3ph-m/followers',
  following_url: 'https://api.github.com/users/jos3ph-m/following{/other_user}',
  gists_url: 'https://api.github.com/users/jos3ph-m/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/jos3ph-m/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jos3ph-m/subscriptions',
  organizations_url: 'https://api.github.com/users/jos3ph-m/orgs',
  repos_url: 'https://api.github.com/users/jos3ph-m/repos',
  events_url: 'https://api.github.com/users/jos3ph-m/events{/privacy}',
  received_events_url: 'https://api.github.com/users/jos3ph-m/received_events',
  type: 'User',
  site_admin: false,
  name: 'Joseph Medina',
  company: 'None',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Licensing by day, developer by night',
  twitter_username: 'jos3ph_m',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
