export default {
  login: 'jos3ph-m',
  id: 53497675,
  node_id: 'MDQ6VXNlcjUzNDk3Njc1',
  avatar_url: 'https://avatars.githubusercontent.com/u/53497675?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jos3ph-m',
  html_url: 'https://github.com/jos3ph-m',
  followers_url: 'https://api.github.com/users/jos3ph-m/followers',
  following_url: 'https://api.github.com/users/jos3ph-m/following{/other_user}',
  gists_url: 'https://api.github.com/users/jos3ph-m/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/jos3ph-m/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jos3ph-m/subscriptions',
  organizations_url: 'https://api.github.com/users/jos3ph-m/orgs',
  repos_url: 'https://api.github.com/users/jos3ph-m/repos',
  events_url: 'https://api.github.com/users/jos3ph-m/events{/privacy}',
  received_events_url: 'https://api.github.com/users/jos3ph-m/received_events',
  type: 'User',
  site_admin: false,
  name: 'Joseph Medina',
  company: null,
  blog: '',
  location: 'Los Angeles',
  email: null,
  hireable: true,
  bio: 'React/Node developer',
  twitter_username: 'jos3ph_m',
  public_repos: 67,
  public_gists: 1,
  followers: 2,
  following: 2,
  created_at: '2019-07-30T22:58:08Z',
  updated_at: '2021-05-11T04:56:06Z',
};
